const data = {
  products: [
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      category: 'Shirts',
      price: 70,
      image: '/images/shirt1.jpg',
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Slim Shirt',
      slug: 'slim-shirt',
      category: 'Shirts',
      price: 78,
      image: '/images/shirt2.jpg',
      brand: 'Adidas',
      rating: 4.8,
      numReviews: 12,
      countInStock: 10,
      description: 'A popular shirt',
    },
    {
      name: 'Golf Pants',
      slug: 'golf-pants',
      category: 'Pants',
      price: 90,
      image: '/images/pants1.jpg',
      brand: 'Raymond',
      rating: 4.1,
      numReviews: 11,
      countInStock: 27,
      description: 'A popular shirt',
    },
    {
      name: 'Fit Pants',
      slug: 'fit-pants',
      category: 'Pants',
      price: 70,
      image: '/images/pants2.jpg',
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      name: 'Classic Pants',
      slug: 'classic-pants',
      category: 'Pants',
      price: 93,
      image: '/images/pants3.jpg',
      brand: 'Casely',
      rating: 3.9,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular pants',
    },
  ],
};

export default data;
